---
- hosts: local
  become: no
  gather_facts: False
  vars:
  tasks:
  - name: Deploy VCDR Connector OVA
    vmware_deploy_ovf:
      hostname: galactica.lab.travellingtechie.com
      username: administrator@vsphere.local
      password: VMware1!
      validate_certs: no
      name: DRaaS-Connector1-01
      datacenter: Homelab
      folder: /Homelab/vm
      cluster: Physical
      datastore: "Lab NFS"
      disk_provisioning: thin
      networks:
        "VM Network": vDS-Production-MGMT
      ova: ~/Downloads/vmware-cloud-connector.ova
      allow_duplicates: no
      power_on: yes
      fail_on_spec_warnings: yes
      wait: yes
      wait_for_ip_address: yes
      inject_ovf_env: yes
    delegate_to: localhost