---
# tasks file for ubuntu_system_prep
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
- name: Create ansible user
  ansible.builtin.user:
    name: "{{ host_ansible_username}}"
    password: "{{ host_ansible_password }}"
    groups: # Empty by default, here we give it some groups
     - sudo
    state: present
    shell: /bin/bash       # Defaults to /bin/bash
    system: no             # Defaults to no
    createhome: yes        # Defaults to yes
    home: /home/mike

# https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html
- name: Set Authorized Key from Rocinante
  ansible.posix.authorized_key:
   user: mike
   state: present
   key: "{{ host_ansible_authorized_key }}"